version: '2'
services:
  jenkins:
    build: ./Jenkins
    ports:
      - "8080:8080"
    tty: true

  jira:
    build: ./Jira
    ports:
      - "8085:8080"
    tty: true

  nexus:
    build: ./Nexus
    ports:
      - "8081:8081"
    tty: true

  urbancode:
    build: ./UrbanCode
    ports:
      - "8089:8080"
      - "8443:8443"
      - "7918:7918"
    tty: true

  zabbix:
    build: ./Zabbix
    ports:
      - "80:80"
      - "10051:10051"
    tty: true
    
  zabbix-agent:
    build: 
      context: ./Zabbix
      dockerfile: AgentDockerfile
    volumes:
      - /:/rootfs
    links:
      - zabbix
    ports:
      - "10050:10050"
    tty: true
